version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/agentforge
      - SECRET_KEY=dev-secret-key-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SERPER_API_KEY=${SERPER_API_KEY:-}
      - ALLOWED_ORIGINS=["http://localhost:3001"]
      - DEBUG=True
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      - db
    networks:
      - agentforge-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - VITE_API_URL=http://localhost:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - agentforge-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: agentforge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agentforge-network

volumes:
  postgres_data:
  backend_data:

networks:
  agentforge-network:
    driver: bridge
